version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-client:
    executor:
      name: node/default
    working_directory: ~/client/
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd client
            - run: ls
            - run: yarn build
workflows:
    build-client:
      jobs:
        - build-client