version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                command: |
                  cd client/
            - run: yarn build
workflows:
    build-client:
      jobs:
        - build-client